[package]
name = "snakebot_rust"
version = "1.1.0"
authors = ["Martin Barksten <martin.barksten@cygni.com>"]
license-file = "LICENSE"

[dependencies]
ws = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
quick-error = "*"
log = "*"
log4rs = { version = "*", features=["toml_format"] }
target_info = "*"
rustc_version = "*"
config = "*"
clap = "*"
