[appenders.console]
kind = "console"

[appenders.console.encoder]
pattern = "{d(%+)(local)} [{t}] {h({l})} {M}:{m}{n}"

[appenders.client]
kind = "file"
path = "log/client.log"

[appenders.snake]
kind = "file"
path = "log/snake.log"

[root]
level = "info"
appenders = [ "console" ]

[loggers.client]
level = "debug"
appenders = [ "client" ]
additive = false

[loggers.snake]
level = "debug"
appenders = [ "console" ]
additive = false
